### ISSUE TITLE
Code problem

### ISSUE THREAD

**Issue by 442413768** [Ryanshuai/BM3D_cpp2py#2] opened 2019-11-29 14:11 UTC
Thank you for your work, will you consider add more comments to your code esp for those parameters with short variable name . Thank you !

**Comment by Ryanshuai** [comment] 2019-11-29 23:13
Duplicate of #3

**Comment by Ryanshuai** [comment] 2019-11-29 23:14
Duplicate of #3

**Closed** 2019-11-29 23:14 UTC
